Clinc.Presentation/ViewModels/AppointmentViewModel.cs
using Clinic.Core.Entities;
using System.ComponentModel.DataAnnotations;

namespace Clinc.Presentation.ViewModels
{
    public class AppointmentViewModel
    {
        [Required]
        public int DoctorId { get; set; }
        public string? DoctorName { get; set; }
        [Required]
        public string PatientName { get; set; }
        [Required]
        public DateTime PatientBD { get; set; }
        [Required]
        public DateTime Date { get; set; }

        //[Required]
        //public string AppointmentTime { get; set; }

        public TimeSpan From { get; set; }
       
        public TimeSpan To { get; set; }
    }
}

Clinc.Presentation/ViewModels/DoctorViewModel.cs
namespace Clinc.Presentation.ViewModels
{
    public class DoctorViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Clinc.Presentation/ViewModels/ErrorViewModel.cs
namespace Clinc.Presentation.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Clinc.Presentation/ViewModels/TimeSlotViewModel.cs
namespace Clinc.Presentation.ViewModels
{
    public class TimeSlotViewModel
    {
        public string TimeSlot { get; set; }
        public TimeSpan From { get; set; }
        public TimeSpan To { get; set; }
    }
}

Clinc.Presentation/Controllers/AppointmentsController.cs
using AutoMapper;
using Clinc.Presentation.ViewModels;
using Clinc.ReponseModel;
using Clinic.Core.Entities;
using Clinic.Core.Interfaces.Services.Contract;
using Microsoft.AspNetCore.Mvc;

namespace Clinc.Presentation.Controllers
{
    public class AppointmentsController : Controller
    {
        private readonly IAppointmentService _appointmentService;
        private readonly IMapper _mapper;

        public AppointmentsController(IAppointmentService appointmentService,IMapper mapper)
        {
            this._appointmentService = appointmentService;
            this._mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult<ResponseModel>> CreateNewAppointment( AppointmentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(new ResponseModel
                {
                    IsSuccess = false,
                    Message = "Invalid data"
                });
            }

            try
            {
                var appointment = _mapper.Map<AppointmentViewModel, Appointment>(model);
                var result = await _appointmentService.CreateNewAppointment(appointment);
                return Ok(result);
            }
            catch (Exception ex)
            {

                throw;
            }
          
        }
    }
}

Clinc.Presentation/Controllers/DoctorsController.cs
using AutoMapper;
using Clinc.Presentation.ViewModels;
using Clinic.Core.Entities;
using Clinic.Core.Interfaces.Services.Contract;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;

namespace Clinc.Presentation.Controllers
{
    public class DoctorsController : Controller
    {
        private readonly IAppointmentService _service;
        private readonly IMapper _mapper;

        public DoctorsController(IAppointmentService service,IMapper mapper  )
        {
            this._service = service;
            this._mapper = mapper;
        }
        public IActionResult Index(int? id)
        {


            return View();
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<AppointmentViewModel>>> GetAppointmentsByDocIdDuringPeriod(int docId,DateTime from,DateTime to)
        {

            var list =await _service.GetAppointmentsByDocIdDuringPeriod(docId,from,to);
            var listOfViewModels = _mapper.Map<IEnumerable< Appointment>,IEnumerable< AppointmentViewModel>>(list);
            return Ok(listOfViewModels);
        }


    }
}

Clinc.Presentation/Controllers/DropDownsController.cs
using AutoMapper;
using Clinc.Presentation.ViewModels;
using Clinic.Core.Entities;
using Clinic.Core.Interfaces.Services.Contract;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Clinc.Presentation.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class DropDownsController : ControllerBase
    {
        private readonly IDcotorsService _dcotorsService;
        private readonly IAppointmentService _appointmentService;
        private readonly IMapper _mapper;

        public DropDownsController(IDcotorsService dcotorsService,IAppointmentService appointmentService ,IMapper mapper)
        {
            this._dcotorsService = dcotorsService;
            this._appointmentService = appointmentService;
            this._mapper = mapper;
        }

        [HttpGet("GetDcotors")]
        public async Task<ActionResult<IEnumerable<DoctorViewModel>>> GetDoctors()
        {
            var doctorsList = await _dcotorsService.GetAllDoctors();
            var doctorsDtoList = _mapper.Map<IEnumerable<Doctor>, IEnumerable<DoctorViewModel>>(doctorsList);
            return Ok(doctorsDtoList);

        }

        [HttpGet("GetFreeTimeSlots")]
        public async Task<ActionResult<IEnumerable<TimeSlotViewModel>>> GetTimeSlotsByDocId(int docId ,DateTime date)
        {
            var freeSlots = await _dcotorsService.GetTheDoctorFreeSlots(docId,date);
            try
            {
                var freeTimeSlotsList = _mapper.Map<IEnumerable<Tuple<TimeSpan, TimeSpan>>, IEnumerable<TimeSlotViewModel>>(freeSlots);
                return Ok(freeTimeSlotsList);
            }
            catch (Exception ex)
            {

                throw;
            }
           
            

        }


    }
}

Clinc.Presentation/Controllers/HomeController.cs
using AutoMapper;
using Clinc.Presentation.Models;
using Clinc.Presentation.ViewModels;
using Clinic.Core.Entities;
using Clinic.Core.Interfaces.Services.Contract;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Clinc.Presentation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IAppointmentService _appointmentService;
        private readonly IMapper mapper;

        public HomeController(ILogger<HomeController> logger,IAppointmentService appointmentService,IMapper mapper)
        {
            _logger = logger;
            this._appointmentService = appointmentService;
            this.mapper = mapper;
        }

        public async Task <IActionResult> Index()
        {
          var listOfAppointments =  await  _appointmentService.GetAllAppointmentsWithDoctorsName();

            var listOfAppointmentsViewModel = mapper.Map<IEnumerable<Appointment>,IEnumerable< AppointmentViewModel >> (listOfAppointments);
            return View(listOfAppointmentsViewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Clinc.Presentation/Views/Appointments/Index.cshtml
@model AppointmentViewModel
@{
    ViewData["Title"] = "Secretary";
}




<div class="container mt-5">
    <h2 class="mb-4">Create New Appointment</h2>
    <form id ="appForm">
        <div class="form-group mb-4">
            <label asp-for="PatientName" >Patient Name</label>
            <input  class="form-control" asp-for="PatientName" placeholder="Enter patient's name" required>
            <span asp-validation-for="PatientName" class="text-danger"></span>
        </div>
        <div class="form-group mb-4">
            <label asp-for="PatientBD">Birth Date</label>
            <input asp-for="PatientBD" type="date" class="form-control" required>
            <span asp-validation-for="PatientBD" class="text-danger"></span>
        </div>
        <div class="form-group mb-4">
            <label asp-for="DoctorId">Choose Doctor</label>
            <select class="form-control" asp-for="DoctorId" required>
               
            </select>
            <span asp-validation-for="DoctorId" class="text-danger"></span>
        </div>
        <div class="form-group mb-4">
            <label asp-for="Date">Appointment Date</label>
            <input asp-for="Date" type="date" class="form-control"  >
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>
        <div class="form-group mb-2">
            <label for="appointmentTime">Appointment Time</label>
            <select class="form-control" id="appointmentTime" required>
                <option value="">Select a time slot</option>
            </select>
            <input asp-for="From"  hidden/>
            <input asp-for="To"  hidden/>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Submit</button>
    </form>
</div>

@section Scripts {
    <script src="~/js/viewjs/appointments.js"></script>
    
    <partial name="_ValidationScriptsPartial" />
}

Clinc.Presentation/Views/Doctors/Index.cshtml
@model AppointmentViewModel
@{
    ViewData["Title"] = "Doctor";
}

<h1>Doctor Appointments:</h1>

<div class="form-group mb-4">
    <label >Choose Doctor</label>
    <select class="form-control" id="doctorsSelect" >
    </select>
</div>
<div class="row" style="padding: 20px;">
    <div class="col-md-6">
        <label>From:</label>
        <div class="input-group" style="width:100%">
            <input type="date" id="startDate" class="form-control" />
        </div>
    </div>
    <div class="col-md-6">
        <label>To:</label>
        <div class="input-group" style="width:100%">
            <input type="date" id="endDate" class="form-control" />
        </div>
    </div>
    <div class="col-md-12 text-center mt-4">
        <button id="searchButton" class="btn btn-primary">Search</button>
    </div>
</div>

<div class="container mt-5" id="dateRange">
    <h2 class="mb-4">Appointments</h2>
    <div id="appointments-container">
        <table id="appointments-table" class="table table-striped">
            <thead>
                <tr>
                    <th>Doctor Name</th>
                    <th>Patient Name</th>
                    <th>Patient Birth Date</th>
                    <th>Appointment Date</th>
                    <th>From</th>
                    <th>To</th>
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
    </div>
    
</div>
@section Scripts {
    <script src="~/js/viewjs/doctors.js"></script>
}

Clinc.Presentation/Views/Home/Index.cshtml
@model IEnumerable<AppointmentViewModel>
@{
    ViewData["Title"] = "Appointments";
}

<div class="container mt-5">
    <h2 class="mb-4">Appointments</h2>

    @if (Model == null || !Model.Any())
    {
        <div class="alert alert-info" role="alert">
            No Appointments.
        </div>
    }
    else
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Doctor Name</th>
                    <th>Patient Name</th>
                    <th>Patient Birth Date</th>
                    <th>Appointment Date</th>
                    <th>From</th>
                    <th>To</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var appointment in Model)
                {
                    <tr>
                        <td>@appointment.DoctorName</td>
                        <td>@appointment.PatientName</td>
                        <td>@appointment.PatientBD.ToString("yyyy-MM-dd")</td>
                        <td>@appointment.Date.ToString("yyyy-MM-dd")</td>
                        <td>@appointment.From</td>
                        <td>@appointment.To</td>
                    </tr>
                }
            </tbody>
        </table>
    }

    <div class="mt-4">
        <a href="@Url.Action("Index", "Appointments")" class="btn btn-primary">Add New Appointment</a>
    </div>
</div>

Clinc.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Clinc | @ViewData["Title"] </title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <!-- SweetAlert2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <link rel="stylesheet" href="~/Clinc.Presentation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary mb-3">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Index">Secretary</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctors" asp-action="Index">Doctors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DMS Egypt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>